ignacio-python-lab_03b
PdxCodeGuild/class_australian_shepherd pull request #44
Opened 2022-08-04 01:39 UTC by RemmyI

2022-08-06 02:51 UTC, cdmichaelb commented on code/ignacio/lab_03b_mad_libs.py
> +    print(nums)
This is just printing the numbers, not the average.

Also, this is titled mad libs but appears to be the average numbers lab.

2022-08-06 02:52 UTC, cdmichaelb commented on code/ignacio/lab_5a_palindrome.py
> +
try again with these two inputs:

"anagram" and "nag a ram"
"anagram" and "Anagram"

Both should be anagrams. Check the assignment for further missing steps.

2022-08-06 02:55 UTC, cdmichaelb commented on code/ignacio/lab_5a_palindrome.py
> +    print(reverse_check)
Shouldn't print inside of a function.

Also, there is no evaluation to see if the word is a palindrome.

2022-08-06 02:55 UTC, cdmichaelb requested changes
Need changes to complete assignments.

2022-08-10 02:13 UTC, ttajohnson approved these changes

2022-08-10 02:27 UTC, cdmichaelb commented
Submitted in #57

2022-08-10 02:27 UTC, closed without merging